### PR TITLE
You are missing some fixes from gedMarcs repo

### PR DESCRIPTION
**Pull request by jogibear9988**
And maybe you could also enable issues?

### CODE REVIEW

**Comment by fklee** [comment]
Hi !

Thanks for the infos . I did this fork long time ago, I will do this as soon as possible.
Ok for the issues !

Maybe,won't be merge all changes.

Let me know if you use it, and don't hesitate to add issues.

**Review by fklee — APPROVED** [review]

**Comment by fklee** [comment]
Hi, @jogibear9988 
Sorry for the delay, but I've now problems to update library to bootstrap v5.0.1 because, they attach the plugin Modal to jquery at the end of loading html (bootstrap function defineJQueryPlugin() ) So when bootstrap dialog want to load the plugin it doesn't yet exist. I update my repo (with error). If you have any idea about this, you're welcome :-)

**Review by fklee — APPROVED** [review]

**Review by fklee — APPROVED** [review]

**Comment by fklee** [comment]
I commit all usefull changes on the branche, wait to find a solution since Bootstrap5 removed jquery, this cause a problem to extend modal bootstrap with jquery.

**Comment by rcarhuaricra** [comment]
Hello, did you find any solution for this?

**Comment by fklee** [comment]
Hello,

No sorry, didn't search any further solution, original bootstrap4-dialog from gedmarc is ok for bootstrap 5. So left this project.

**Pull request closed without merging**
